### ISSUE TITLE
FR - Automatic templates

### ISSUE THREAD

**Issue by Jopp-gh** [technohiker/obsidian-multi-properties#31]
Adding custom property fields to a folder with notes is nice, but way too slow and awkward on the long run.

For multiple notes, I'd prefer a popup button to choose from "property templates" I made. 

Also, adding properties to single, existing notes should be automatic, if desired or use a popup button to choose templates

**Comment by SeaOfBloodRedRoses** [comment]
I'm not sure if you already know this and maybe I'm misinterpreting what you've written, but there is a way to create templates.

Settings > Core Plugins > Templates > Template folder location
Create a folder and select it in the path. Create your templates and add them to the folder. On the far left of the left pane, there's an insert template button. Click that and a list of your templates will pop up.
You need to have the text box selected in order to insert a template. It will not insert if you just have the file selected, or if your cursor is over the title.
Therefore, it unfortunately doesn't work for multiple new files. However, you could also copy existing files once you've added the template, if you need mass template creation .

**Comment by SeaOfBloodRedRoses** [comment]
Ah, I gotcha!
I hope I didn't misimply anything: I can't actually help with this. Not the
coding part at all. I hope your request gets addressed though!

**Comment by technohiker** [comment]
> adding properties to single, existing notes should be automatic, if desired or use a popup button to choose templates

This is already possible with the Templates core plugin.  Define a template with yaml headers in your Template folder.  Next go to the top line of your note(below the title, above any notes you typed in) and use the Insert Template hotkey.(no hotkey by default, you'll need to bind your own).  You'll be prompted to select a note from your Template folder.  From there you select the note with the desired yaml template, and the note will have those Property names.

> For multiple notes, I'd prefer a popup button to choose from "property templates" I made.

The Templater community plugin has similar functionality where a template will automatically be added to a new note in a specified folder.  However, there is currently no functionality for mass-adding a template to all existing notes in a folder/selection.

I still plan on making the GUI the only way you interact with Multi-Properties.  However, I'm going to look into whether or not I can get the plugin to look for a specified Template file, and have it load into the GUI.  If it works, this should strike a good compromise.

**Comment by technohiker** [comment]
This has been addressed in version 1.2.0.  There is now an option in Settings that lets you list a file with Properties and they will be auto-loaded into the GUI.
